version: "3"
services:
  mcp:
    container_name: nextcloud-live-instance-mcp
    build: .
    command: ["python", "main.py"]
    ports:
      - "8000:8000"
    environment:
      NEXTCLOUD_URL: "http://nc32-app-1:80"   # or http://host.docker.internal:8031 for local dev
      NEXTCLOUD_USERNAME: "NEXTCLOUD_USERNAME"
      NEXTCLOUD_APP_TOKEN: "NEXTCLOUD_APP_TOKEN"
    networks:
      - testnet

networks:
  testnet:
    external: true
